name = "notion-maps"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-03-09"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"

# [secrets]
# MAPKIT_TEAM_ID
# MAPKIT_PRIVATE_KEY_ID
# MAPKIT_PRIVATE_KEY
# NOTION_API_KEY
