name: Build
on:
  push:
  pull_request:
  repository_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
         apiToken: ${{ secrets.CF_API_TOKEN }}
         secrets: |
           MAPKIT_TEAM_ID
           MAPKIT_PRIVATE_KEY_ID
           MAPKIT_PRIVATE_KEY
           NOTION_API_KEY
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          MAPKIT_TEAM_ID: ${{ secrets.MAPKIT_TEAM_ID }}
          MAPKIT_PRIVATE_KEY_ID: ${{ secrets.MAPKIT_PRIVATE_KEY_ID }}
          MAPKIT_PRIVATE_KEY_BASE64: ${{ secrets.MAPKIT_PRIVATE_KEY }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
